sudo: false
dist: trusty
language: node_js
node_js:
- '8'
before_install:
- if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
- npm install
before_script:
  - npm install -g bower
  - bower install
script:
- eslint src
- wct --plugin sauce
notifications:
  email: false
addons:
  sauce_connect:
  #$ sudo gem install travis
  #$ travis encrypt travis encrypt SAUCE_ACCESS_KEY=Your Sauce Labs access key --add
    username: dgt41
  jwt: 
    secure: kFs3XP3b3Xn3JGXW/OHUf8Z4CQoAUY1x9ySYSTaBs6QhOcqfGX3cjaeNlGXHcfYqSA8v698Ts1bzaxU2lW9c4R77GHlzIsS0YRmDW+DJtkNvTRRKGnZyUXDd8pjXVth8YzVNpw9vrSI7QQCd9OZhfNQ0mxtEIcfqOWM39yiwvPjY74WNHH9/j/l0tSGAyZT1rA0rhSkSrq0XVyLmE6nXz3xKi87RInKBeXCCcbq8ocXrB/Fi5lBMQw6RNnjd6c4d3rwDbQoTRoBekuKDf2Zw1mODDJIS7cqicb3ou2yOjDOeAF1lPwOppXKPJ7o57OGfiKKmSB6siHh8DXsTDohyuZ1wh0DWp+16H1FWHlfPbhUaV5625ilaxTGGn8Ans43jnHb+f4pqJHzeLE1h43Ly/9jhdHsvXMPd6uFrrxyMbmPzsXWb6SUrJKRkSoICQWWqduaDpdxjlRg7nMgOPjLZYqiKSrw5ArGv+PjAFAWn4jTscYDjpukoUdCZy0wjKS7I1krTE/hP5juNR+gjqJYmeH0djR+y2nrjHuwzK043z69qAwcWC4IKTEKHMNRTKf5kbWkFPJDf1t6naJ4g0P8bntOfHrNfhbMD/VtIUAff5TLYozLhezjq/nXRuM3bT/PSUIelD9RpO9xxYgEF8V1+RTaZ8OV/hZz/17eRJA9VsSc=
