sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
  - npm install
script:
  - eslint src
notifications:
  email: false
