name: Browser Testing

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    name: Sauce Labs

    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip

      # - uses: actions/checkout@v2

      # - uses: actions/setup-node@v1
      #   name: Set up NodeJS
      #   with:
      #     node-version: [ 14 ]

      # - name: Install
      #   run: npm install

      # Sause Labs part
      - uses: saucelabs/sauce-connect-action@v1.1.3
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accesskey: ${{ secrets.SAUCE_ACCESS_KEY }}
          scVersion: 4.6.4
          tunnelIdentifier: github-action-tunnel-custom-elements-${{ github.run_id }}
          # github-action-tunnel-custom-elements-${process.env.GITHUB_RUN_ID}

      # Run the tests
      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run ci-test
