name: Browser Testing

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    name: Sauce Labs
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Set up NodeJS
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          scVersion: 4.6.4
          tunnelIdentifier: github-action-tunnel
      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm ci-test


