# This action will run the build script and merge back the distribution files

name: Distribution

on: [push, pull_request, pull_request_target]

jobs:
  distribution:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present

    - uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: Adding back the distribution files...
        branch: ${{ github.head_ref }}
